<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Jellyfin.Plugin.ShareLinks</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.ShareLinks</AssemblyName>
    <Version>1.1.0.1</Version>
    <AssemblyVersion>1.1.0.1</AssemblyVersion>
    <FileVersion>1.1.0.1</FileVersion>
    <Authors>Franciskid; Ruslan Veselov</Authors>
    <RepositoryUrl>https://github.com/rakkateichou/jellyfin-plugin-sharelinks</RepositoryUrl>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="12.1.0" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Web\**\*.*" />
  </ItemGroup>

</Project>
